experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
  dataset: facebook_book
  top_k: 10
  evaluation:
    cutoffs: [10]
    simple_metrics: [nDCGRendle2020]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:   
    external.LightGCN:
      meta:
        verbose: True
        save_recs: True
        validation_rate: 2    
        tsne_sizes : [2,4,8,16,32,64]  
        pca_sizes :  [2,4,8,16,32,64]  
        kpca_sizes : [2,4,8,16,32,64]  
      lr: 0.0028462729478462134
      epochs: 2
      factors: 64
      batch_size: 64
      l_w: 0.06184015598288455
      n_layers: 3
      seed: 123
      
    