experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: C:\Users\zanzo\Documents\GitHub\AIML-LIGHT_GCN\data\facebook_book\train.tsv
    validation_path: C:\Users\zanzo\Documents\GitHub\AIML-LIGHT_GCN\data\facebook_book\val.tsv
    test_path: C:\Users\zanzo\Documents\GitHub\AIML-LIGHT_GCN\data\facebook_book\test.tsv
  dataset: facebook_book
  top_k: 10
  evaluation:
    cutoffs:
    - 10
    simple_metrics:
    - nDCGRendle2020
  gpu: 1
  external_models_path: ../external/models/__init__.py
  models:
    external.LightGCN_Custom:
      meta:
        verbose: 'true'
        save_recs: 'true'
        validation_rate: 1
        dataset_name: facebook_book
        reducers_types: []
        reducers_factors: []
        KPCA_Kernels: []
        tsne_reducers_factors:
        - 2
        hyper_max_evals: 20
        hyper_opt_alg: tpe
        validation_metric: nDCGRendle2020@10
      epochs: 200
      factors: 256
      batch_size: 64
      l_w: 0.009707538210675435
      lr: 0.0001095050831578516
      n_layers: 3
      seed: 123
      early_stopping:
        patience: 5
        mode: auto
        monitor: nDCGRendle2020@10
        verbose: true
