experiment:
  backend: tensorflow
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
    side_information:
      - dataloader: KGFlexLoader
        item_features: ../data/{0}/kgflex/item_features.tsv
  dataset: movielens
  top_k: 10
  evaluation:
    cutoffs: [10]
    simple_metrics: [nDCGRendle2020]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.KGFlex:
      loader: KGFlexLoader
      meta:
        verbose: True
        save_recs: True
        validation_rate: 9
      lr: 0.05794172109229535
      embedding: 1
      epochs: 9
      max_features_per_user: 1000
      batch_size: 2048
