experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
  dataset: movielens
  top_k: 50
  evaluation:
    cutoffs: [50]
    simple_metrics: [nDCGRendle2020]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    MostPop:
      meta:
        verbose: True
        save_recs: True
    Random:
      meta:
        verbose: True
        save_recs: True
    external.BPRMF:
      meta:
        verbose: True
        save_recs: True
        validation_rate: 89
      lr: 0.0003087013410270289
      batch_size: 2048
      epochs: 89
      factors: 64
      l_w: 0.006008395850822256
      seed: 123
    EASER:
      meta:
        verbose: True
        save_recs: True
      l2_norm: 1156.7327374740782
    external.LightGCN:
      meta:
        verbose: True
        save_recs: True
        validation_rate: 113
      lr: 0.00023352280052445944
      epochs: 113
      factors: 64
      batch_size: 2048
      l_w: 0.040674109767529866
      n_layers: 3
      seed: 123
    external.DGCF:
      meta:
        verbose: True
        save_recs: True
        validation_rate: 95
      lr: 0.00022272775385254683
      epochs: 95
      factors: 64
      batch_size: 2048
      l_w_bpr: 0.0003402025321070952
      l_w_ind: 0.00010533228394991676
      ind_batch_size: 2048
      n_layers: 1
      routing_iterations: 2
      intents: 4
      seed: 123
    ItemKNN:
      meta:
        verbose: True
        save_weights: False
        validation_metric: nDCGRendle2020@10
        save_recs: True
      neighbors: 200
      similarity: cosine
      seed: 123
