experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
  dataset: yahoo_movies
  top_k: 10
  evaluation:
    cutoffs: [10]
    simple_metrics: [nDCGRendle2020]
  gpu: 1
  external_models_path: ../external/models/__init__.py
  models:
    MostPop:
      meta:
        verbose: True
        save_recs: False
    Random:
      meta:
        verbose: True
        save_recs: False
    external.BPRMF:
      meta:
        hyper_max_evals: 20
        hyper_opt_alg: tpe
        verbose: True
        save_recs: False
        validation_rate: 1
        validation_metric: nDCGRendle2020@10
      lr: [ loguniform, -9.210340372, -5.298317367 ]
      batch_size: 256
      epochs: 200
      factors: 64
      l_w: [ loguniform, -11.512925465, -2.30258509299 ]
      seed: 123
      early_stopping:
        patience: 5
        mode: auto
        monitor: nDCGRendle2020@10
        verbose: True
    external.LightGCN:
      meta:
        hyper_max_evals: 20
        hyper_opt_alg: tpe
        verbose: True
        save_recs: False
        validation_rate: 1
        validation_metric: nDCGRendle2020@10
      lr: [ loguniform, -9.210340372, -5.298317367 ]
      epochs: 200
      factors: 64
      batch_size: 256
      l_w: [ loguniform, -11.512925465, -2.30258509299 ]
      n_layers: 3
      seed: 123
      early_stopping:
        patience: 5
        mode: auto
        monitor: nDCGRendle2020@10
        verbose: True
    external.DGCF:
      meta:
        hyper_max_evals: 20
        hyper_opt_alg: tpe
        verbose: True
        save_recs: False
        validation_rate: 1
        validation_metric: nDCGRendle2020@10
      lr: [ loguniform, -9.210340372, -6.90775527898 ]
      epochs: 200
      factors: 64
      batch_size: 256
      l_w_bpr: [ loguniform, -9.21034037198, -4.60517018599 ]
      l_w_ind: [ loguniform, -9.21034037198, -4.60517018599 ]
      ind_batch_size: 256
      n_layers: 1
      routing_iterations: 2
      intents: 4
      seed: 123
      early_stopping:
        patience: 5
        mode: auto
        monitor: nDCGRendle2020@10
        verbose: True
    ItemKNN:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        validation_metric: nDCGRendle2020@10
        restore: False
        save_recs: False
      neighbors: [ 50, 200, 400, 600, 1000 ]
      similarity: [ cosine, jaccard, dice, dot ]
      seed: 123
