experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: C:\Users\zanzo\Documents\GitHub\AIML-LIGHT_GCN\data\yahoo_movies\train.tsv
    validation_path: C:\Users\zanzo\Documents\GitHub\AIML-LIGHT_GCN\data\yahoo_movies\val.tsv
    test_path: C:\Users\zanzo\Documents\GitHub\AIML-LIGHT_GCN\data\yahoo_movies\test.tsv
  dataset: yahoo_movies
  top_k: 10
  evaluation:
    cutoffs: [10]
    simple_metrics: [nDCGRendle2020]
  gpu: 1
  external_models_path: ../external/models/__init__.py
  models:
    external.LightGCN_Custom:
      meta:
        hyper_max_evals: 20
        hyper_opt_alg: tpe
        verbose: true
        save_recs: false
        validation_rate: 1
        validation_metric: nDCGRendle2020@10
        dataset_name: yahoo_movies
        reducers_types: []
        reducers_factors: []
        KPCA_Kernels: []
        tsne_reducers_factors:
        - 2
      lr: [loguniform, -9.210340372, -5.298317367]
      epochs: 200
      factors: 128
      batch_size: 256
      l_w: [loguniform, -11.512925465, -2.30258509299]
      n_layers: 3
      seed: 123
      early_stopping:
        patience: 5
        mode: auto
        monitor: nDCGRendle2020@10
        verbose: true
