experiment:
  backend: tensorflow
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
    side_information:
      - dataloader: KGINTSVLoader
        kg: ../data/{0}/kgin/kg.tsv
  dataset: yahoo_movies
  top_k: 50
  evaluation:
    cutoffs: [50]
    simple_metrics: [nDCGRendle2020]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    KGIN:
      meta:
        verbose: True
        save_recs: True
        validation_rate: 55
      lr: 0.0007862193934678993
      batch_size: 256
      epochs: 55
      l2: 0.025150249382470014
      lfr: 1.1290993113924475e-05
      emb: 64
      hops: 3
      n_fac: 4
      n_drop: True
      n_drop_r: 0.5
      m_drop: True
      m_drop_r: 0.1
      ind: distance
      seed: 123
      loader: KGINTSVLoader
