experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
    side_information:
      - dataloader: KAHFMLoader
        kg_train: ../data/{0}/kahfm/kg.tsv
  dataset: yahoo_movies
  top_k: 50
  evaluation:
    cutoffs: [50]
    simple_metrics: [nDCGRendle2020]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    KaHFMEmbeddings:
      meta:
        verbose: True
        save_recs: True
        validation_rate: 145
      epochs: 145
      batch_size: 256
      lr: 0.0003087013410270289
      l_w: 0.006008395850822256
      l_b: 0
      loader: KAHFMLoader
      seed: 123
